package me.ez.orebushes.Datagen;

import me.ez.orebushes.Main;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.data.event.GatherDataEvent;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;

/**
 * Data generation.
 *
 * <p>{@link GatherDataEvent} is abstract since 26.1. Per the NeoForge recommendation, every
 * provider (client and server) is registered on {@link GatherDataEvent.Client} and generated by a
 * single {@code runClientData} run. Generating client and server datagen in separate runs would
 * make the vanilla hash cache purge the other side's output, since both share
 * {@code src/generated/resources}.
 */
@EventBusSubscriber(modid = Main.MOD_ID)
public class DataGen {

    @SubscribeEvent
    public static void onGatherClientData(GatherDataEvent.Client event) {
        DataGenerator generator = event.getGenerator();
        PackOutput output = generator.getPackOutput();
        event.addProvider(new LanguageProvider(output, "en_us"));
        event.addProvider(new ModRecipeProvider.Runner(output, event.getLookupProvider()));
        event.addProvider(new LootTableProvider(output, event.getLookupProvider()));
    }
}
